---
- name: Deploy Docker Projects to EC2
  hosts: web_nodes
  become: yes
  vars:
    docker_username: "praveen0031"
    ansible_python_interpreter: /usr/bin/python3
    projects:
      - { name: "pro1", port: "8081" }
      - { name: "pro2", port: "8082" }
      - { name: "pro3", port: "8083" }
      - { name: "pro4", port: "8084" }

  tasks:
    - name: Install Docker and Dependencies
      yum:
        name: 
          - docker
          - python3-pip
        state: present

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ec2-user is in docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Run Node Exporter for Prometheus Metrics
      shell: |
        docker pull prom/node-exporter:latest
        docker stop node-exporter || true
        docker rm node-exporter || true
        docker run -d \
          --name node-exporter \
          --restart always \
          --net="host" \
          --pid="host" \
          -v "/:/host:ro,rslave" \
          -p 9100:9100 \
          prom/node-exporter:latest

    - name: Pull and Run All Project Containers (Direct Command)
      shell: |
        docker pull {{ docker_username }}/{{ item.name }}:latest
        docker stop {{ item.name }}-container || true
        docker rm {{ item.name }}-container || true
        docker run -d \
          --name {{ item.name }}-container \
          --restart always \
          -p {{ item.port }}:80 \
          {{ docker_username }}/{{ item.name }}:latest
      loop: "{{ projects }}"